### ISSUE TITLE
试用链接无法访问

### ISSUE THREAD

**Issue by gaozhengjie** [qiuhuachuan/smile#10]
您好，您提供的体验链接 http://47.97.220.53:8080/ 已无法访问，是否后台已停止服务，还考虑继续启动服务吗？

**Comment by qiuhuachuan** [comment]
您好，会考虑继续启动服务的，最近服务器崩了，在修复中

**Comment by qiuhuachuan** [comment]
考虑到GPU资源的问题，暂时不部署了。
