### ISSUE TITLE
请问您是怎么制作这么多的数据集的呀

### ISSUE THREAD

**Issue by Franklin-L** [qiuhuachuan/smile#11]
求助大佬如何制作数据集，可以指点一下吗

**Comment by Franklin-L** [comment]
我想制作单论对话的数据集，类似于特定场景的百科，这个应该怎么去制作呀

**Comment by qiuhuachuan** [comment]
从工程的角度，你可以这么写prompt.

根据一下的文本，写一个单轮的QA对话。
文本：正态分布（英语：Normal distribution），又名高斯分布（英语：Gaussian distribution）、正规分布，是一个非常常见的连续概率分布。

以下是ChatGPT的生成结果：
用户：正态分布是什么意思？

ChatGPT：正态分布，也称为高斯分布或正规分布，是一种非常常见的连续概率分布。它在统计学和概率论中有广泛的应用，用来描述大量自然现象和随机变量的分布特征。

**Comment by qiuhuachuan** [comment]
你可以参考我的论文里的方法，就是如何提示模型去完成一个特定的任务。

**Comment by Franklin-L** [comment]
> 你可以参考我的论文里的方法，就是如何提示模型去完成一个特定的任务。

嗷嗷前辈我刚刚仔细阅读了您的论文，是将单论对话生成为多轮对话吗，那也就是说需要先准备单轮对话吗

**Comment by Franklin-L** [comment]
> 从工程的角度，你可以这么写prompt.
> 
> 根据一下的文本，写一个单轮的QA对话。 文本：正态分布（英语：Normal distribution），又名高斯分布（英语：Gaussian distribution）、正规分布，是一个非常常见的连续概率分布。
> 
> 以下是ChatGPT的生成结果： 用户：正态分布是什么意思？
> 
> ChatGPT：正态分布，也称为高斯分布或正规分布，是一种非常常见的连续概率分布。它在统计学和概率论中有广泛的应用，用来描述大量自然现象和随机变量的分布特征。

通过这样先让chatgpt生成针对一些方面的单轮对话，然后再用这个生成多轮对话吗
