### ISSUE TITLE
关于微调

### ISSUE THREAD

**Issue by RyanOvO** [qiuhuachuan/smile#12]
请问，基于自己的数据集，如何接入微调？感谢

**Comment by RyanOvO** [comment]
微调流程是否如下所示：
按文档的训练流程，以及经过转换后的数据结构组织数据，即可进行微调。

**Comment by qiuhuachuan** [comment]
是的呢

**Comment by qiuhuachuan** [comment]
> 微调流程是否如下所示： 按文档的训练流程，以及经过转换后的数据结构组织数据，即可进行微调。

参考“模型训练”，有任何问题都可以找我联系哈
