### ISSUE TITLE
作用还是有限

### ISSUE THREAD

**Issue by riichg5** [qiuhuachuan/smile#2]
聊了半天，感觉没啥用啊

**Comment by qiuhuachuan** [comment]
是的，因为现有数据是从壹心理的单轮QA改写得到，并且多轮对话继承了原数据中提供非常多建议的情况，在我的论文第二个版本中有分析，目前投稿中（涉及匿名期，并未更新，后续可以给您分享）。
其次，现在的模型更多的是倾听陪伴，还没有达到真人咨询师一般，可以在恰当的时机去帮助用户探索、或者挑战用户，甚至一些发散性的提问，现有模型都很难做到。

如果您有更多关于提升模型对话能力的建议，欢迎留言。
Thanks.

**Comment by riichg5** [comment]
我现在也在基于GLM2 6B(不排除改用其他模型)训练特定性格特点的角色，看到你这个项目，所以试用了一下。你的训练结果和我预期的差不多。我现在还在收集和处理语料。

**Comment by gaozhengjie** [comment]
> 是的，因为现有数据是从壹心理的单轮QA改写得到，并且多轮对话继承了原数据中提供非常多建议的情况，在我的论文第二个版本中有分析，目前投稿中（涉及匿名期，并未更新，后续可以给您分享）。 其次，现在的模型更多的是倾听陪伴，还没有达到真人咨询师一般，可以在恰当的时机去帮助用户探索、或者挑战用户，甚至一些发散性的提问，现有模型都很难做到。
> 
> 如果您有更多关于提升模型对话能力的建议，欢迎留言。 Thanks.

您第二个版本论文公开的时候，希望有机会能第一时间拜读一下。

**Comment by gaozhengjie** [comment]
> 我现在也在基于GLM2 6B(不排除改用其他模型)训练特定性格特点的角色，看到你这个项目，所以试用了一下。你的训练结果和我预期的差不多。我现在还在收集和处理语料。

您好，我最近也刚接触心理咨询这个领域，但是我发现目前关于这方面公开的数据似乎很少。请问您是从什么渠道收集的语料呢，方便分享一下经验吗？

**Comment by riichg5** [comment]
> 

语料是前提条件，效果要好，那必须有高质量的语料，这个是垂直领域的核心竞争力了。你如果没有行业内部数据做支撑（这个我相信不是外面随便能收集到的），即便有很好的模型做基础，也不会有理想的结果。

**Comment by qiuhuachuan** [comment]
> 我现在也在基于GLM2 6B(不排除改用其他模型)训练特定性格特点的角色，看到你这个项目，所以试用了一下。你的训练结果和我预期的差不多。我现在还在收集和处理语料。

如果你深入去分析一下数据，会分析出数据的pattern。举个例子，你可以看到每条支持者回复都是共情+建议，其实这种pattern在真实心理咨询场景是有问题的，我在我论文的第二版中进行了专业咨询师的盲评，模型的回复还是比不过真人咨询师回复。

**Comment by qiuhuachuan** [comment]
> > 我现在也在基于GLM2 6B(不排除改用其他模型)训练特定性格特点的角色，看到你这个项目，所以试用了一下。你的训练结果和我预期的差不多。我现在还在收集和处理语料。
> 
> 您好，我最近也刚接触心理咨询这个领域，但是我发现目前关于这方面公开的数据似乎很少。请问您是从什么渠道收集的语料呢，方便分享一下经验吗？

您可以看我第一版的论文，有介绍如何收集数据的。就是使用ChatGPT 将QA改写为多轮对话。

**Comment by qiuhuachuan** [comment]
> 

确实如此。目前我也看到后续有和我差不多的工作出来，我看了下他们放出的对话示例，大同小异。

**Comment by riichg5** [comment]
收集好的语料很花成本
