### ISSUE TITLE
可以交流一下吗，按照您的方法训完之后碰到问题

### ISSUE THREAD

**Issue by sunlin-xiaonai** [qiuhuachuan/smile#3]
本机显存24g， 内存16g， 训练完成后加载模型直接都加载到内存里面去了，直接内存爆了跑不起来，求助

**Comment by qiuhuachuan** [comment]
您好，关于您遇到的训练问题，显存不足以支持最低的memory，只能增加加载模型的显存，或者使用int 8量化后的模型试试。

我训练的时候使用的是A100 80G显存的卡，如果您还有其他问题，欢迎交流。

您可以参考这个链接下的模型 https://huggingface.co/THUDM/chatglm-6b-int8
因为训练和推理是不同的，如果这个也不行，那只能换训练设备。

**Comment by sunlin-xiaonai** [comment]
我看了加载到吗，进行了一下修改让他直接加载到了gpu上不过，询问问题后出现了一个新的错误让我不知所措。
<img width="933" alt="image" src="https://github.com/qiuhuachuan/smile/assets/129371884/5775b18a-36c5-4322-8b63-1e4b4f4caa0f">
<img width="838" alt="image" src="https://github.com/qiuhuachuan/smile/assets/129371884/793f3e7c-4c20-4ef2-ab09-e45d88a9703c">

**Comment by qiuhuachuan** [comment]
我感觉初始权重不应该挂载到GPU，需要等LoRA权重加载后，再挂载到GPU。

**Comment by sunlin-xiaonai** [comment]
提前把模型挂在gpu 中在去加载权重和在cpu 加好移到gpu 中有什么不同么？在一个就是我挂在后，访问报错上面的130000not in list 这个错误要怎么修改呢，很奇怪

**Comment by sunlin-xiaonai** [comment]
还有一个问题是现在训练好的参数可以直接和已经量化了的模型配合使用？可以直接用还是说还需要重新训练呢？

**Comment by qiuhuachuan** [comment]
这个我没有试过哈，您可以试试哈

**Comment by sunlin-xiaonai** [comment]
嗯嗯排除万难起来了，不过访问一段时间后就会出现阻塞状态，服务器端显示在计算，但是接口不没有响应，这个是什么情况呢？

**Comment by qiuhuachuan** [comment]
要不杀掉进程，重新启动试试
