### ISSUE TITLE
你好，如果对对话大模型进行微调，请问使用什么方法对微调前后的数据集进行评估比较优劣？

### ISSUE THREAD

**Issue by wuQi-666** [qiuhuachuan/smile#6]

**Comment by qiuhuachuan** [comment]
自动化评估，如BLEU-1/2/3/4, Distinct-1/2/3/4, METEOR, Perplexity, Rouge-L

人工评估：指标需要自己定义，比如流畅度、一致性、共情得分、有效建议得分

**Comment by wuQi-666** [comment]
感谢你的回答，以上你提供的自动化评估方式是NLP生成任务重通用的评价指标。我只是使用心理领域对话数据在大模型上进行微调，然后使用同样的测试集，调用微调前后的模型，生成对应的对话测试数据集，我目前使用GPT3.5，设置prompt，让GPT3.5自动对微调前后测试集回答效果进行打分。但是GPT3.5的打分评估结果没有什么差距。所以求助您在心理领域对微调前后测试集评估的方法？

**Comment by qiuhuachuan** [comment]
我在我的论文中使用了真实的咨询对话数据，让模型生成回复，将模型生成的回复和原本的真实回复进行盲评，让咨询师选择哪一个回复你更喜欢。具体指标可以从心理咨询的角度出发。

**Comment by wuQi-666** [comment]
好的，非常感谢你的回答
