### ISSUE TITLE
AttributeError: 'ChatGLMForConditionalGeneration' object has no attribute 'lm_head'

### ISSUE THREAD

**Issue by Sun0308** [qiuhuachuan/smile#7]
![image](https://github.com/qiuhuachuan/smile/assets/141383166/c614a80a-1f73-4b58-95c7-0b73f7ae0314)
model.lm_head = CastOutputToFloat(model.lm_head)

**Comment by qiuhuachuan** [comment]
ChatGLM-6b 和ChatGLM2-6b两者之间架构的差异，会造成这个问题。
