### ISSUE TITLE
数据集基础情况了解

### ISSUE THREAD

**Issue by jakeywu** [qiuhuachuan/smile#8]
您好， 请问plain、smile、smile_cot数据集有什么差别呢

**Comment by qiuhuachuan** [comment]
1. plain，又名为standard，即0-shot的情况，纯粹输入指令让模型生成数据，这会在真实性、多样性都不好
2. smile是引入了真实的QA（可视为单轮对话），真实性和多样性都可以得到提升
3. smile_cot只是在smile的基础上加入了一句神奇咒语let us think step by step，其实我们发现引入这个神奇咒语对任务并没有性能上的提升，即数据集的质量不会有很好的提升，有可能变差

综上，我们会在近期发布我们论文的第二版，论文中会详述他们的区别，敬请关注。

**Comment by jakeywu** [comment]
非常感谢。 
如此我理解：意味着我们在sft的时候，首先采用smile数据集嘛。 毕竟plain是0-shot产生的数据，smile_cot感觉过于推理化，不具备跳跃性，不切合实际生活。不知道是否正确，请指教

另外： 三类数据是如何构成的能否讲解一下呢。 比如plain是基于什么模型0-shot产生的呢， 指令的构成方式；smile为什么说是真实的QA；smile_cot是谁添加的神奇咒语

**Comment by qiuhuachuan** [comment]
您好，关于细节可以参考我们的论文，里面有详细的阐述与比较：https://github.com/qiuhuachuan/smile/blob/main/paper/SMILE_Single_turn_to_Multi_turn_Inclusive_Language_Expansion_via_ChatGPT_for_Mental_Health_Support.pdf
