### ISSUE TITLE
训练过程的问题

### ISSUE THREAD

**Issue by TheShy-Dream** [qiuhuachuan/smile#9]
你好，是不是最新版本的smile还不支持训练呀，我用的是V1分支的版本在训练，出现了如下问题，
![image](https://github.com/qiuhuachuan/smile/assets/58178926/b0cd5fd5-7869-4026-9087-45005d786c94)
打印的内容是
![image](https://github.com/qiuhuachuan/smile/assets/58178926/7c27b8f0-ae45-4a76-b0ae-58a40078e676)
我不知道为什么输出的都是nan，然后报错RE

**Comment by qiuhuachuan** [comment]
您好，v1分支的训练代码适合chatglm-6b，和chatglm2-6b是不兼容。

**Comment by TheShy-Dream** [comment]
收到，辛苦了，祝万事如意，笑口常开，更上一层楼。

**Comment by TheShy-Dream** [comment]
嗯嗯，请问当前main分支的(基于chatglm微调)的代码会开源吗，当前好像只有数据转换的脚本，没有训练的脚本，期待开源，谢谢咯!

**Comment by qiuhuachuan** [comment]
代码会开源的哈
